### ISSUE TITLE
[BUG] Offhand takes items from hotbar rather than inventory

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#100]
**Describe the bug**
Offhand should prioritise inventory over hotbar as it is annoying having hotbar being shuffled for no reason.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use offhand 
2. Have offhand take a gap or crystal out of your hotbar
3. See result

**Expected behavior**
Offhand should prioritise taking items from your inventory rather than hotbar to make it less annoying and so you only ever have totems in your inventory rather than in your hotbar.

**Comment by TechAle** [comment]
Im creating a new offhand and i arleady fixed it

**Comment by TechAle** [comment]
Close this

**Comment by Doogie13** [comment]
closed by #106
