### ISSUE TITLE
[BUG] AutoTrap

### ISSUE THREAD

**Issue by Phantom568** [IUDevman/gamesense-client#101]
**Describe the bug**

If you toggle it while not having obsidian in your hotbar it kicks you from the server for "invalid hotbar selection(Hacking!?)"

**To Reproduce**
1. toggle auto trap without obsidian in your hotbar

**Expected behavior**
Should just either disable or pull obsidian from inventory

**Screenshots**
No need for screenshots 

**Desktop (please complete the following information):**
 - Current version

**Comment by TechAle** [comment]
Ill fix this now, it should be easy

**Comment by TechAle** [comment]
Fixed, ill publish it on my next commit. Close this issue

**Comment by TechAle** [comment]
fixed in #106
