### ISSUE TITLE
MCF [BUG]

### ISSUE THREAD

**Issue by Phantom568** [IUDevman/gamesense-client#110]
**Describe the bug**
Middle click friend(MCF) seems to be adding people when right clicking instead of middle clicking to add

**To Reproduce**
1. Turn on the module
2. Right click any player 
3. You have now added a friend

**Expected behavior**
The expectation is to use the middle mouse button to add people instead of right click

**Comment by IUDevman** [comment]
Sounds like an easy fix!!! New module: RCF !!!!!!!! 

i kid

**Comment by IUDevman** [comment]
fixed
