### ISSUE TITLE
PacketFly/Phase[FEATURE]

### ISSUE THREAD

**Issue by AiryXV** [IUDevman/gamesense-client#113]
**Is your feature request related to a problem? Please describe.**
well I've always had to use other clients which makes it a bit annoying to manage 5 clients at a time 
would be great if gamesense had this.

**Describe the solution you'd like**
Lets you phase throught blocks

**Describe alternatives you've considered**
Might wanna consider future or pyro pfly

**Additional context**

**Comment by notperry1234567890** [comment]
phase :face_with_raised_eyebrow:

**Comment by frosthead69** [comment]
creepy salhack
