### ISSUE TITLE
[BUG] OnUpdate

### ISSUE THREAD

**Issue by 0b00101010** [IUDevman/gamesense-client#127]
**Describe the bug**
On update gets called twice per tick

**To Reproduce**
Print out time difference between each OnUpdate loop and a pattern 50, 1, 50, 1, 50, 1 appears (or something similar).

**Expected behavior**
Not reallly sure.

**Additional context**
This is quite important as changing this could break certain modules (which is why I didnt just make a pull request).
ClientTickEvent has a Post and Pre phase and currently gamsense runs OnUpdate on both.
Wasn't sure what was the best way to fix it.

**Comment by IUDevman** [comment]
I think this runs as intended, but let's talk about this further in the discord.
