### ISSUE TITLE
Pressing TAB to open the Tablist crashes my game

### ISSUE THREAD

**Issue by happyspeler** [IUDevman/gamesense-client#145]
So i just installed Gamesense and when i open the Tablist my game crashes.

Mods i use:

Optifine (Fast render and Fast math is disabled)
KAMI Blue

[video here!](https://youtu.be/WLbFtJXowMY)

**Comment by lukflug** [comment]
Would be useful to know what modules you had enabled and to get the crash report in form of a text file.

**Comment by happyspeler** [comment]
Modules:

AutoCrystalGS
Chams
Watermark

**Comment by IUDevman** [comment]
I have a feeling you're running Wurst2+ aswell. Never had that issue with GS, but that is a fairly common issue for Wurst2+

**Comment by happyspeler** [comment]
Thanks i will try it!
