### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Pirobit** [IUDevman/gamesense-client#153]
game crashes during load 
[crash-2021-02-10_08.59.15-client.txt](https://github.com/IUDevman/gamesense-client/files/5958640/crash-2021-02-10_08.59.15-client.txt)

help i cant use gamesense

**Comment by 0b00101010** [comment]
This seems to be a problem with impact

**Comment by IUDevman** [comment]
Impact

**Comment by B2H990** [comment]
If you get impact to load before gamesense it solves this issue

**Comment by Pirobit** [comment]
yeah that is what helped
