### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Sahil-108** [IUDevman/gamesense-client#154]
**Is your feature request related to a problem? Please describe.**
Not a bug a suggestion
antiburrow

**Describe the solution you'd like**
Basically it stops players from burrowing
For example autoanvil it uses pressure plates
so if u place a pressure plate under a player they cant place a block

**Describe alternatives you've considered**
Not many Ive tried recreating it with my own code but Im new to java so that didnt work

**Additional context**

**Comment by IUDevman** [comment]
This sounds pretty cool.

**Comment by IUDevman** [comment]
The latest version of HoleFill includes a setting that will only target holes near an enemy. I will add an option for pressure plates once I resolve #177.
