### ISSUE TITLE
Add scaling damage to AutoCrystal

### ISSUE THREAD

**Issue by WooHooASDF** [IUDevman/gamesense-client#157]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I have the opportunity to pop an oponents totem, by dealing a little bit of extra damage to myself, however it is above the max self damage on the autocrystal.

**Describe the solution you'd like**
A scaling mode for max self damage, allowing you to get the last few hits in to pop someone, for example, If a crystal could do 20 damage to the oponent and 8 to me, which is more than my max self damage, allow it to place and destroy the crystal.

**Comment by Doogie13** [comment]
My theory on how it could work

- damageRatio meaning 1:n where n is how much damage you deal and 1 is how much you take (setting how much value each crystal should have to make it worth doing extra damage)

- maxDamageRatio would set the max damage you take including damage ratio (so you don't take 20 damage per crystal on people with no armour taking 100 damage or something, also top of _/‾ where x is damage and y is self damage)

- minDamageRatio would set the point where it bottoms out ( bottom of _/‾)

- allowTotemPop would let you pop yourself (self explainaatory)

Note: setting min and maxDamageRatio to the same would make this function like normal maxdamage as the graph is flat at whatever level you want)

Idk if this idea of how to set it up is practical but it seams easy enough to use as a user

**Comment by WooHooASDF** [comment]
I was thinking about the same thing

**Comment by IUDevman** [comment]
@0b00101010 might be something to consider with your AC rewrite

**Comment by 0b00101010** [comment]
Seem like a good idea, will look into implementing it

**Comment by IUDevman** [comment]
Merged with #220
