### ISSUE TITLE
[FEATURE] Breadcrumbs Bypass

### ISSUE THREAD

**Issue by linustouchtips** [IUDevman/gamesense-client#158]
**Is your feature request related to a problem? Please describe.**
Right now, GameSense breadcrumbs does not bypass servers with a strict NCP config, this is infuriating when I am pvping and I can't see where I've walked before. I have personally baby raged over this at least 5 times.

**Describe the solution you'd like**
A server-side breadcrumbs should help bypass both ping and anticheat compatability.

**Describe alternatives you've considered**
Pyro+, Blackdoored, Quillish, Momentum, GameSense Blue, Velocity+, Wurst+3, Kami Red

**Additional context**
![SIL_BreadCrumbs_Kikkoman_Panko_mjqflj](https://user-images.githubusercontent.com/68214996/108006475-67b87080-6fb0-11eb-8068-d3adb33230ec.png)

**Comment by IUDevman** [comment]
I promise that I will look into this!

**Comment by linustouchtips** [comment]
please! i need this.

**Comment by Doogie13** [comment]
im so excited to see this implimented. (no other client has this yet!!!!!!!!!!!!!!!!!!!!!!!!!)
