### ISSUE TITLE
Rendering bug with optifine

### ISSUE THREAD

**Issue by WooHooASDF** [IUDevman/gamesense-client#160]
**Describe the bug**
A rendering bug with optifine causes blocks to become transparent upon changing dimension.

**To Reproduce**
Dowload optifine and gamesense, log onto a serve, change dimension, and observe.

**Expected behavior**
it should render normaly

**Screenshots**
![2021-02-16_13 22 54](https://user-images.githubusercontent.com/76736350/108069255-0ef1e200-705b-11eb-91a1-bfeab59c20ef.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by IUDevman** [comment]
I'm currently working on replicating this issue. I know that I myself and others use optifine and do not have this issue, so can you attach your optifine settings?

I can recall that there was a setting in optifine which breaks most renders, but I don't recall which one.

**Comment by IUDevman** [comment]
try turning off fast render

**Comment by WooHooASDF** [comment]
Ok, Thanks
