### ISSUE TITLE
[FEATURE] Hole Fill Enemy only

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#161]
**Is your feature request related to a problem? Please describe.**
Hole fill fills any hole

**Describe the solution you'd like**
Make an option for hole fill to only fill the nearest hole to the opponent

**Describe alternatives you've considered**
placing one block manually 

**Additional context**
other similar modules could benefit from this (web fill)

**Comment by linustouchtips** [comment]
god damn it

**Comment by linustouchtips** [comment]
im never joining gamesense vc again

**Comment by Doogie13** [comment]
> im never joining gamesense vc again

LMAO

**Comment by TechAle** [comment]
i'm adding this, but, since this should be a feature of momentum, this is going to have a cost u.u

**Comment by TechAle** [comment]
added #168 , close this
