### ISSUE TITLE
The bug that I'm experiencing is when I have gamescene and phobs_1.9_clean then the hole esp and esp on the block that the crystal will place on will turn grey and ive tried chancing the color settings but the color just stays gray[BUG]

### ISSUE THREAD

**Issue by ManOfMemes** [IUDevman/gamesense-client#163]
- **Describe the bug**

**To Reproduce**
Steps to reproduce the behavior:1. Go to Minecraft with gamescence and phobos gopro366
2. Turn on crystalaura &hole esp
3. go into the settings and try to configure the color of the esp
4. it will stay grey after agusting the color settings

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 2.2.6]

**Additional context**
Add any other context about the problem here (e.g. screenshots, videos)

**Comment by IUDevman** [comment]
I believe that this may be a phobos issue. Our renders do not break other clients except for salhack. I'm closing this for now, but feel free to reopen this issue if you can provide any errors thrown (eg: from the game output).
