### ISSUE TITLE
[FEATURE]A module like FuckedDetector from Wurst+2

### ISSUE THREAD

**Issue by CornyDogger** [IUDevman/gamesense-client#167]
Renders the players lower hitbox in a different colour when they're in a spot that can be crystalled at full damage
![fuckeddetector](https://user-images.githubusercontent.com/62382872/108187556-70e63200-70c3-11eb-8a7b-bf7163ae9cd9.png)

**Comment by IUDevman** [comment]
Added, It's called "Bucked" because I'm not really interested in naming a module "Fucked"
