### ISSUE TITLE
[FEATURE] Offhand feature

### ISSUE THREAD

**Issue by Sahil-108** [IUDevman/gamesense-client#172]
**Is your feature request related to a problem? Please describe.**
Basically to sum it up its like the old gs offhand where u could bind offhand crystal and gapple to keys like old gs

**Describe the solution you'd like**
P much old gs offhand with 2.2.7's reaction/speed of replacing ur item

**Describe alternatives you've considered**
I think a few other clients like phobos have this

**Additional context**
idk

**Comment by IUDevman** [comment]
> everyone asks for different method off offhand

> We do it

> Now you want it back ????????
