### ISSUE TITLE
[FEATURE] To rewrite

### ISSUE THREAD

**Issue by IUDevman** [IUDevman/gamesense-client#187]
Below is a list of things which could be rewrote for next or future versions:

# Modules
Combat:
- [ ] AutoArmor
- [ ] AutoCrystalGS
- [ ] HoleFill

Misc:
- [ ] Announcer
- [ ] AutoTool
- [ ] PvPInfo

Render:
- [ ] NoRender

# Other
- [ ] Mixins- needs major cleanup
- [ ] Add more managers for things such as placements and maybe offhand

**Comment by Sahil-108** [comment]
Something abt holefill rewrite lime is there away u guys could implement a double hole file if its already in idk my brain stops working past 5am

**Comment by IUDevman** [comment]
> Something abt holefill rewrite lime is there away u guys could implement a double hole file if its already in idk my brain stops working past 5am

On my mind!
