### ISSUE TITLE
[FEATURE] Armor destroy in autocrystal

### ISSUE THREAD

**Issue by SomePineaple** [IUDevman/gamesense-client#193]
**Is your feature request related to a problem? Please describe.**
No its not related to a problem

**Describe the solution you'd like**
I think that the autocrystal should have an armor destroy mode, so it will face place if the target has low armor

**Describe alternatives you've considered**
I tried to do this myself but I'm confused about how ur autocrystal works, and I couldn't get it to work.

**Comment by IUDevman** [comment]
@0b00101010 maybe a feature for your rewrite?

**Comment by Doogie13** [comment]
i thought it existed already but was set to 25%?

**Comment by 0b00101010** [comment]
Shouldn't be too difficult to implement. Will look into it.

**Comment by IUDevman** [comment]
Merged with #220
