### ISSUE TITLE
[FEATURE] Mode BOTH For Chams

### ISSUE THREAD

**Issue by nekounderscore** [IUDevman/gamesense-client#197]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I Mode in chams where both wireframe and fill are enabled

**Comment by IUDevman** [comment]
Would be a great commit for an aspiring contributor 👀

**Comment by Doogie13** [comment]
> Would be a great commit for an aspiring contributor 👀

might try this but am monke at coding

**Comment by olliem5** [comment]
okay

**Comment by nekounderscore** [comment]
> Would be a great commit for an aspiring contributor 👀

shut
