### ISSUE TITLE
[FEATURE] ArrayList HUDInfo Alignement

### ISSUE THREAD

**Issue by zihasz** [IUDevman/gamesense-client#208]
**Is your feature request related to a problem? Please describe.**
Yes, the problem is that in the ArrayList the modules with a HUDInfo dont line up with the ones that don't have one. 

**Describe the solution you'd like**
The modules line up, I think the solution should be fairly easy.
The solution I thought of would be to have:
```java
module.getHudInfo() != "" ? module.getName() + ChatFormatting.GRAY + " " + module.getHudInfo() : module.getName()
```
instead of
```java
module.getName()+ChatFormatting.GRAY+" "+module.getHudInfo()
```
and
```java
module.getHudInfo() != "" ? module.getName() + ChatFormatting.GRAY + " " + module.getHudInfo() : module.getName()
```
instead of
```java
module.getName() + ChatFormatting.GRAY + " " + module.getHudInfo();
```

**Describe alternatives you've considered**
I tried fixing myself but it didn't work.

**Additional context**
http://ignorelist.me/e33327b21714

**Comment by IUDevman** [comment]
Fixed thanks!

**Comment by zihasz** [comment]
Thank you for the quick reply and fix! This is the stupidest and smallest thing but it was annoying me so bad.
