### ISSUE TITLE
[BUG]Gui Scale Not Working

### ISSUE THREAD

**Issue by XdFag** [IUDevman/gamesense-client#210]
**The Gui Scale Is Not Working**
The Gui Scale Is Not Changing.

**To Reproduce**
2. Turn on '...'
3. Toggle '...'

**Expected behavior**
so last night i updated to 2.2.8 and after i did all the config stuff, i went to bed then when i woke up and started mc, its gui scale was set to auto and when i changed it to normal, nothing happened.

**Screenshots**

**Information:**
 - OS Windows 10
 - Version 2.28
 - Other mods used phobos 1.9 gs compatible

**Additional context**
I tried to delete the .minecraft folder but it still wasnt changing

**Comment by lukflug** [comment]
GameSense and PanelStudio don't even deal with GUI scaling right now, closed for trolling.
