### ISSUE TITLE
[BUG] autotrap rotations

### ISSUE THREAD

**Issue by SoggyBacco** [IUDevman/gamesense-client#221]
on stricter servers autotrap can get u kicked for invalid rotations

**Comment by IUDevman** [comment]
What servers?

**Comment by notperry1234567890** [comment]
> on stricter servers autotrap can get u kicked for invalid rotations

using autotrap moment

**Comment by TechAle** [comment]
i have fixed this on pistonCrystal, now i'll fix it on autotrap
