### ISSUE TITLE
[FEATURE]Min Health Option for piston crystal

### ISSUE THREAD

**Issue by XdFag** [IUDevman/gamesense-client#224]
So usually when i use piston crystal, when i am on low health, i cant eat the gap 
that makes the enemy have a good chance of killing me

So Add a min health option
so when the health goes below to a certain amount of health it automaticly pauses piston crystal

**Comment by TechAle** [comment]
Gotcha, ill add it in the next commit

**Comment by TechAle** [comment]
added in #225 , hossier close this and merge my pr
