### ISSUE TITLE
[FEATURE]Missing Features

### ISSUE THREAD

**Issue by XdFag** [IUDevman/gamesense-client#230]
**Is your feature request related to a problem? Please describe.**
When I suggest gamesense to my friends, they always say it isn't good cause it doesn't have some of the most basic features

**Describe the solution you'd like**
i suggest adding antikb(velocity) and scaffold

**Describe alternatives you've considered**
what do i put here?

**Additional context**

**Comment by IUDevman** [comment]
velocity already exists, no one is forcing you to not use another client with gamesense
