### ISSUE TITLE
[FEATURE] InstantMine / Packet mine render

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#235]
**Is your feature request related to a problem? Please describe.**
enemy gamers keep killing me

**Describe the solution you'd like**
An option for packetmine to render the block being broken and for instantmine to render the block being spammed as well.
Could render the progress but idk if thats feasable

**Describe alternatives you've considered**
Ares has the instantmine render thing 

**Additional context**
Fortnite

**Comment by CyberHydra** [comment]
Demoman Gaming

**Comment by Doogie13** [comment]
> Demoman Gaming

Demoknight TF2

**Comment by IUDevman** [comment]
Can add a render for what our module is targeting, but other than that we're out of luck :P

**Comment by Doogie13** [comment]
> Can add a render for what our module is targeting, but other than that we're out of luck :P

ye thats what i meant

**Comment by TechAle** [comment]
Added
