### ISSUE TITLE
[FEATURE] MCP

### ISSUE THREAD

**Issue by zihasz** [IUDevman/gamesense-client#242]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like scaffold and middle click pearl so i dont have to use 4 clients.

**Describe alternatives you've considered**
I've been using 4 clients instead of 2 and my load times are really slow.

**Additional context**
No.

**Comment by IUDevman** [comment]
I will be adding MCP!

**Comment by TechAle** [comment]
maybe i'll add scaffold since i want to experiment with knockback modification

**Comment by IUDevman** [comment]
Added
