### ISSUE TITLE
[BUG] Chams EChest top

### ISSUE THREAD

**Issue by zihasz** [IUDevman/gamesense-client#243]
**Describe the bug**
When using texture chams, the top if ender chests bug out and disappear. 

**To Reproduce**
1. Turn on Chams
2. Set mode to Texture
3. Place an echest
4. The ender chest texture bugs out.

**Expected behavior**
I would expect it to not bug out

**Screenshots**

**Information:**
 - OS: Windows 10 20H2
 - Version: latest dev build as of 2021.03.28.
 - Mods: GameSense, OptiFine, RusherHack (cracked), Surge, Trinity, Xulu

**Additional context**
None.

**Comment by IUDevman** [comment]
I'll look into it

**Comment by IUDevman** [comment]
Can confirm this is a thing- I'll see about fixing it.

**Comment by phobologicalt** [comment]
how tf you get optifine to work it doesnt for me
