### ISSUE TITLE
[BUG] OffHand crash

### ISSUE THREAD

**Issue by zihasz** [IUDevman/gamesense-client#244]
**Describe the bug**
When using GameSense the OffHand module crashes my game.

**To Reproduce**
1. Turn on OffHand
2. Play
3. Crash

**Expected behavior**
For my game not to crash.

**Screenshots**
None

**Information:**
 - OS: Windows 10 20H2
 - Version: latest dev build as of 2021.03.28.
 - Mods: GameSense, OptiFine, RusherHack (cracked), Surge, Trinity, Xulu

**Additional context**
https://pastebin.com/jWVM2UmM
Settings:
```json
{
  "Module": "Offhand",
  "Settings": {
    "Default": "Totem",
    "NonDefault": "Crystal",
    "NoPlayer": "Gapple",
    "Potion": "first",
    "HealthSwitch": 10,
    "TickDelay": 0,
    "FallDistance": true,
    "MaxSwitch": 5,
    "BiasDamage": 1.0,
    "PlayerDistance": 0.0,
    "PickObby": false,
    "PickObbyOnShift": false,
    "CrystShiftObby": false,
    "LeftClickGap": true,
    "ShiftPot": false,
    "OnlySword": true,
    "CrystalCheck": true,
    "NoHotBar": true,
    "OnlyHotBar": false,
    "AntiWeakness": true,
    "HotBarTotem": false
  }
}
```

**Comment by TechAle** [comment]
i should have fixed this bug yesterday

**Comment by IUDevman** [comment]
Fixed
