### ISSUE TITLE
i have this wierd render issue when using gs[BUG]

### ISSUE THREAD

**Issue by papahappa** [IUDevman/gamesense-client#246]
**Describe the bug**
when i use gamesense the player in inv is transparent and sometimes when i open guy some blocks get transparent

**To Reproduce**
idk how this works 
![2021-03-28_21 34 20](https://user-images.githubusercontent.com/71063011/112758777-af99d100-900d-11eb-8bcb-cf52588918e2.png)

**Expected behavior**

**Screenshots**

**Information:**
 - OS [e.g. Windows 10]
 - Version [e.g. 2.2.8]
 - Other mods used [list all of them]

**Additional context**
Add any other context about the problem here (e.g. screenshots, videos)
![2021-03-28_21 34 24](https://user-images.githubusercontent.com/71063011/112758766-a01a8800-900d-11eb-9113-e7df60b142f6.png)

**Comment by Phantom568** [comment]
This is due to the no render module more specifically the "no cluster" setting as for the transparent blocks you get you need to turn off fast render in optifine and it should be fine asking in the discord usually gets answers faster :)

**Comment by KMatias123** [comment]
this happens to me too with fast render turned off
i think it has something to do with future since im using future too
