### ISSUE TITLE
[FEATURE] Setting in CevBreaker

### ISSUE THREAD

**Issue by tescomealdeal** [IUDevman/gamesense-client#258]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A Setting in CevBreaker that toggles FastBreak breaker mode

**Comment by IUDevman** [comment]
@TechAle

**Comment by TechAle** [comment]
Added in #255 
I decided to not integrate a breaker on cevbreak, but to integrate a button that force breaker to be actived on fastbreak,
so ya, you have to bind at the same key / have it actived before
