### ISSUE TITLE
AutoCrystal Option NoGapSwitch

### ISSUE THREAD

**Issue by Oecher1** [IUDevman/gamesense-client#26]
AutoCrystal Option NoGapSwitch basically you got gap in your main hand it wont switch to crystals so you can gap without having to be popped because it will switch you can kinda fix this with pause health but eh i feel like NoGapSwitch option would just be better.

**Comment by Oecher1** [comment]
> AutoCrystal Option NoGapSwitch basically you got gap in your main hand it wont switch to crystals so you can gap without having to be popped because it will switch you can kinda fix this with pause health but eh i feel like NoGapSwitch option would just be better.

Actually having it not switch if your eating the gapple would be better.

**Comment by IUDevman** [comment]
Added option! Will be in next release.
