### ISSUE TITLE
[BUG] rotations kick the player

### ISSUE THREAD

**Issue by KMatias123** [IUDevman/gamesense-client#261]
**Describe the bug**
using rotations in autotrap (or any other module that includes rotating the players head) kicks for invalid rotations on latest ncp

**To Reproduce**
try to autotrap a player with rotations on on a server with latest updated nocheatplus

**Expected behavior**
i wont get kicked for invalid rotations and the player will get trapped fine

**Screenshots**
none

**Information:**
 - OS: fedora 33
 - Version: happens in both 2.2.8 and one of the latest dev builds
 - Other mods used: future client, autobot, terra, viaforge, optifine

**Additional context**
the video is recorded on meteorpvp
https://www.youtube.com/watch?v=L_9aNDvpAf0

**Comment by IUDevman** [comment]
What servers?

**Comment by TechAle** [comment]
In every servers that requires rotation on,
for some reasons that i dont know, if your y rotation is > 0, it fuck up everything at it make an illegal rotation

**Comment by IUDevman** [comment]
> In every servers that requires rotation on,
> for some reasons that i dont know, if your y rotation is > 0, it fuck up everything at it make an illegal rotation

So this a new thing or what?

**Comment by KMatias123** [comment]
yaw is -90 to 90 afaik

**Comment by IUDevman** [comment]
Yeah I can add in a limiter see how it works.
