### ISSUE TITLE
[FEATURE] Quiver

### ISSUE THREAD

**Issue by tbdontop** [IUDevman/gamesense-client#274]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add a quiver module so it's a bit faster to apply positive effects. When pressing the keybind it will automatically make the player shoot an arrow with a positive effect that will hit the player using the module and when it has finished applying the effect it will toggle off. 

**Describe alternatives you've considered**
Taking a few seconds to aim an arrow that will hit my player.

**Comment by Sahil-108** [comment]
SelfBow is already a module

**Comment by IUDevman** [comment]
Merged with #280
