### ISSUE TITLE
[FEATURE] AntiBurrow/AntiHoleCamp

### ISSUE THREAD

**Issue by tescomealdeal** [IUDevman/gamesense-client#275]
**Describe the solution you'd like**
a module that places a piston next to someone in a hole then a redstone torch/block next to it to power the piston, then the piston pushes the player outve the hole

**Additional context**
something to holefill the hole the target player was pushed outve would be a nice addition to this module

**Comment by Sahil-108** [comment]
im p sure techale had this in mind but I think its a good idea idk
