### ISSUE TITLE
[FEATURE] 2.3.1 Feature Map

### ISSUE THREAD

**Issue by IUDevman** [IUDevman/gamesense-client#280]
A summary of things that have been requested:
1. As usual, burrow.
2. Quiver #274
3. Day time module thing (set the time of the sky) #269
4. Trajectories
5. Sideways rainbow option

**Comment by IUDevman** [comment]
@olliem5

**Comment by olliem5** [comment]
I'll get to work on these once I'm back from my trip.

**Comment by TechAle** [comment]
Add also this:
- echest farmer (relbu's idea)
- cape visible from other gamesense users (maybe we could also add custom capes like on konas)
- elevatot

**Comment by IUDevman** [comment]
More to-dos:
1. Add switch back to AutoCity in CityESP.
2. Work on improving general switch functions, aka no more switching back on disable (switch back once the placement is done) and adding in silent switch.

```
mc.player.connection.sendPacket(new CPacketHeldItemChange(slot));
mc.playerController.syncCurrentPlayItem();
```
