### ISSUE TITLE
Crystal per second counter[FEATURE]

### ISSUE THREAD

**Issue by YoungGarbage** [IUDevman/gamesense-client#281]
@olliem5 , ψ ï̷̲̎ ̴̡̖̄̓s̶͔̺̠̝͌p̶̧̛̘͈̼̋̐̀̄a̸͔̰͐͋͛w̸̱̰̟̄͆́̌͂n̵̳̜̓ ̶̨̨̪̟̾̽̌́̐y̶͔̎̓ȏ̵̡͝ŭ̷͍̌̐̾̋ ⛥
I would like a crystal per second counter, preferably on the HUDeditor menu, it can look like a coordinate shower, but just ___ crystals/s

It will be useful to configurate the correct settings for Gamesense's CA, or any other CA. It will also be useful because settings of how fast a CA is on paper is very different with what it is on a real cpvp, like fluctuation of ping, low tps, and many other stuff

I'm not a coder but 
```static HashMap<Player, HashMap<EntityType, Integer>>
onDamageEntity(Player) {
       //add the integer with the type
}``` 
this is my best guess on how it will look like

thank you very much in advance! 🅱️

**Comment by kritacal** [comment]
can you make piston aura 1.16.5 place?

**Comment by YoungGarbage** [comment]
> can you make piston aura 1.16.5 place?

You can make your own enhancement issue for that, put it on fabric-gamensense's github

**Comment by World-Alt** [comment]
mhm

**Comment by olliem5** [comment]
I have an idea on how to do this, I’ll try some things and see what I can do, it should work regardless of what AutoCrystal you’re using.
