### ISSUE TITLE
[FEATURE] Packetmine esp or smthin

### ISSUE THREAD

**Issue by scaffoldd** [IUDevman/gamesense-client#284]
PacketMine but shows when its ready and not ready like
red - not ready
green - ready
idk

**Comment by TechAle** [comment]
We have an option that switch to the pick when its ready

**Comment by TechAle** [comment]
I think this is enough if you want a fast packet mine

**Comment by scaffoldd** [comment]
It doesnt show when its done it just shows what block it's mining thats all

**Comment by scaffoldd** [comment]
and like i would want like it shows when ready
cuz its pretty cool

**Comment by TechAle** [comment]
Tbh, i think that the switch we have now its enough, if you dont need a fast packet mine, i think you can switch to a pick whenever you want and the block will be ready, just wait some seconds

**Comment by linustouchtips** [comment]
He's referring to a packet mine render, not the speed of the packetmine itself

**Comment by TechAle** [comment]
oh, i was sleepy and dumb, i'll make  it

**Comment by scaffoldd** [comment]
> He's referring to a packet mine render, not the speed of the packetmine itself

Yes i meant that thanks!

**Comment by TechAle** [comment]
just added, i'll push the update tomorrow with one new module

**Comment by scaffoldd** [comment]
Pog, Thanks!

**Comment by scaffoldd** [comment]
> just added, i'll push the update tomorrow with one new module

When doe 👀

**Comment by TechAle** [comment]
Technically i have already done it, its in my pull request, this night ill finish a new module and then ill ask to hossier to merge this. If you want to use it max 1 day before the merge, you can download the artifact

**Comment by scaffoldd** [comment]
alright
thanks

**Comment by scaffoldd** [comment]
> Technically i have already done it, its in my pull request, this night ill finish a new module and then ill ask to hossier to merge this. If you want to use it max 1 day before the merge, you can download the artifact

damm.... its really nice 10/10

**Comment by linustouchtips** [comment]
please close this issue
