### ISSUE TITLE
A module to not render players you are inside

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#29]
Stop this happening in crystal PVP.
![2020-10-31_12 57 46](https://user-images.githubusercontent.com/62295632/97779850-ca5c3c80-1b78-11eb-9918-af260d8e10f8.png)
Context: I am trying to mine this gamers obsidian near his feet.
An alternative is kami-blue esp set up to not render the player. this works fine until you use intel graphics (when it breaks and makes it worse). 

Edit: why the fuck do my tracers in impact have a bend in them?

**Comment by Doogie13** [comment]
I was only using impact because it boots faster for the screenshot.

**Comment by lukflug** [comment]
I believe older Intel Graphics don't support OpenGL 3.2. The KAMI and GameSense tessellators, however use `GL_DEPTH_CLAMP`.

**Comment by linustouchtips** [comment]
i know how to solve this, feature will be added in next release of gamesense
