### ISSUE TITLE
[FEATURE] Anti-Burrow

### ISSUE THREAD

**Issue by TalentedToad** [IUDevman/gamesense-client#291]
places a redstone block/torch and a piston and pushes the person out of the burrow

**Comment by TechAle** [comment]
Its in my plan for 2.3.1.

**Comment by TechAle** [comment]
+ we already have an issue with this, close

**Comment by olliem5** [comment]
elevator :trollface:

**Comment by Sahil-108** [comment]
elevatot*

**Comment by Xiaro** [comment]
Time for AntiAntiBurrow
