### ISSUE TITLE
pistoncrystal multi [FEATURE]

### ISSUE THREAD

**Issue by phobologicalt** [IUDevman/gamesense-client#297]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
I think it would be cool if it could do more then 1 crystal with piston crystal, like from several sides it would place a couple pistons and it would do more damage because of more crystals. Also another thing that would be cool is if the crystalaura could forceplace when there is a block above it making it unable to place in vanilla. 

**Describe alternatives you've considered**
doing it manually

**Comment by TechAle** [comment]
this is really dumb lol, that's not how it works
