### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yourrree** [IUDevman/gamesense-client#299]
**Describe the bug**

**To Reproduce**
2. Turn on '...'
3. Toggle '...'

**Expected behavior**

**Screenshots**

**Information:**
 - OS [e.g. Windows 10]
 - Version [e.g. 2.2.6]
 - Other mods used [list all of them]

**Additional context**
Add any other context about the problem here (e.g. screenshots, videos)

**Comment by IUDevman** [comment]
yes
