### ISSUE TITLE
[BUG] Error: Main method not found in class com.gamesense.client.GameSense

### ISSUE THREAD

**Issue by Errorcrafter** [IUDevman/gamesense-client#300]
**Describe the bug**
After cloning into this repo to use as reference for a client I'm making [(](https://www.reddit.com/r/minecraftclients/comments/lq1xyi/faq_answered_20/)skid i know but every other decent client base is horribly outdated), I decided to use IntelliJ's built in run as Minecraft Client feature to test if it actually worked. However, upon launching the Minecraft Client, this error message appears:
```java
Error: Main method not found in class com.gamesense.client.GameSense, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```
I added the following at the bottom of `GameSense.java`, underneath `private void startClient()` to try and solve the issue:
```java
public static void main(String[] args) {
    System.out.print("In main()");
}
```
but the Minecraft Client was not launched and the following was printed to console
```java
In main()
Process finished with exit code 0
```

**To Reproduce**
Steps to reproduce the behavior (may not work idk):
1. Go into command line and `git clone https://github.com/IUDevman/gamesense-client/`
2. Configure all the necessary gradle stuffs through command line
3. Go into IntelliJ (I used IntelliJ IDEA Community Edition 2020.3 x64)
4. Press this button in the top-right corner: 
![image](https://user-images.githubusercontent.com/69189354/115979235-547cdf00-a5b7-11eb-81e3-db75c3d0d7de.png)
5. Error

**Expected behavior**
Minecraft Client running GameSense d2.3.1 should load normally

**Information:**
 - **OS:** Windows 10 Pro N version 20H2 OS build 19042.928
 - **Version:** d2.3.1 (cloned from git two days ago, unmodified)
 - **Other mods used:** None, but I have the MinecraftDev intellij plugin installed

**Comment by lukflug** [comment]
You're running it as an stand-alone Java application. You should be running it using `runClient` or `build` it and run it in the launcher.

**Comment by Errorcrafter** [comment]
@lukflug, thank you for your reply. After using `runClient` i got the following crash log: https://ghostbin.co/paste/wu6vzj2

Sorry for any inconvenience caused.

**Comment by lukflug** [comment]
So this is something that happens when the mixins aren't loaded for some reason.
Try running `setupDecompWorskpace`, if you haven't already and then `genIntellijRuns` to be able to run it via IntelliJ.
If it creates that error again, you can work around it by running `build` and using the generated jar in the launcher.

**Comment by Errorcrafter** [comment]
I have already run the two commands you have recommended (though i used `gradlew idea genIntellijRuns` instead) and still nothing. are you sure there is no other way than to build the client? I was hoping that I could use gradle to launch it within my IDE like i do with fabric mods
