### ISSUE TITLE
[BUG] Autoinventory/autogear cannot save to or read from json (linux)

### ISSUE THREAD

**Issue by epicfacethe3rd** [IUDevman/gamesense-client#301]
the `gear` command can't do anything at all in terms of saving or adding things

**To Reproduce**
1. load up gamesense on linux
2. do any `gear` command
3. watch it instantly fail

**Expected behavior**
literally any other output

**Information:**
 - Ubuntu 20.04
 - latest release 
 - Future, forgehax, journeymap, schematica, optifine, world downloader

**Additional context**
happened on a friend's skid that i was working with, tried official release and got the same issue

**Comment by IUDevman** [comment]
Aight we'll look into it.

**Comment by tbdontop** [comment]
then dont use linux ezpz

**Comment by epicfacethe3rd** [comment]
> then dont use linux ezpz

cringe
