### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PhobosRat** [IUDevman/gamesense-client#302]
GUI is invisible
when i press o to open the GUI, my mouse pops up as if the gui was open, but i cant see it. i tried binding it to other keys but it doesnt change anything. 

**To Reproduce**
2. Turn on '...'
3. Toggle '...'

**Expected behavior**

**Screenshots**

**Information:**
 - OS [e.g. Windows 10]
 - Version [e.g. 2.2.6]
 - Other mods used Kami Blue, Wurstplustwo]

**Additional context**
Add any other context about the problem here (e.g. screenshots, videos)

**Comment by lukflug** [comment]
You know that you are supposed to *fill out* the fields in the pull request template?
Try typing `-fixgui` in chat.
