### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Relbu** [IUDevman/gamesense-client#303]
**Is your feature request related to a problem? Please describe.**

nope

**Describe the solution you'd like**

I have 2 suggestions, make an image option for the csgo gui. You'd select the image by making a texture pack with the desired texture in assets/gamesense/csgo.png (like how future handles textures) or simply replacing an image in the assets folder within the jar. This image would appear as a background for the csgo gui rather than it being a static color/rainbow.  If this is not possible, simply making gradient possible between 2 custom colors would be cool.

My other suggestion, which might be a pain in the ass depending on how you coded the client. An option where you could type in desired name and It'll replace all the gamesense text, examples being chat notifications, top left of csgo gui, watermark etc. Although the option to simply change the csgo GUI text would be well enough for me.

**Comment by Relbu** [comment]
I just thought of another suggestion, being able to drag specific categories out of the csgo gui. You'd drag the specific category and it would appear like an exeter Section next to the CSGO gui. This would also shrink the csgo gui to fit the other categories without leaving a blank space at the top. You'd need to make settings for modules automatically shrink along with the gui though so that might be a challenge.

A command like .show del/add which would prevent certain modules from appearing in both guis, so you can do .show del NoFall for example and then it wouldnt appear in the gui. This would be good to make the gui cleaner and easier to navigate.

**Comment by mwahaha9** [comment]
Why would they let you change the name? If you want to change at least out in the effort of skidding the client

**Comment by Relbu** [comment]
> Why would they let you change the name? If you want to change at least put in the effort of skidding the client

its just the same concept like with phobos, maybe i want it to say Aimware or onetap, i dont see the harm? You're acting like im taking away credit or smth from the client whilst screensharing. Skidding it would just be inconvenient, needing to skid every update that gets released is a pain in the ass.

**Comment by IUDevman** [comment]
@lukflug

**Comment by lukflug** [comment]
Yes that would be possible.

**Comment by Relbu** [comment]
@lukflug but is it worth ur time...

**Comment by lukflug** [comment]
Idk, I'll finish PanelStudio first
