### ISSUE TITLE
Silent Switch Option[FEATURE]

### ISSUE THREAD

**Issue by WebFag** [IUDevman/gamesense-client#310]
**Is your feature request related to a problem? Please describe.**
gamesense keeps on switching to obsidian when i use holefiller

**Describe the solution you'd like**
silent fill option for holefiller and autoweb

**Describe alternatives you've considered**
idk
**Additional context**

**Comment by yagel15637** [comment]
Silent fill is just desync 101, and you can't do anything with your original item while spoofing your hotbar.
