### ISSUE TITLE
Offhand improvements

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#32]
Offhand should be one module because they directly conflict.
OH should optionally switch to a totem or gap (user selects) if CA is not on. 
OH should have the option to switch to a gap in a hole
OH should optionally be able to switch from inventory as a priority over hotbar
A good example is Wurst+2

Thanks!

**Comment by Doogie13** [comment]
Sorry if I come off as demanding but I just want to help improve the client!

**Comment by Doogie13** [comment]
Sorry if I come off as demanding but I just want to help improve the client!

**Comment by IUDevman** [comment]
All good, I added some offhand toggle options. I think this should solve your issue, if not I'll re open this for next release.

**Comment by Doogie13** [comment]
Just opening this to ask for smart offhand which would switch to a crystal only when crystal aura is on and otherwise will hold a golden Apple in a hole and a totem outside of one. Basically w+2 offhand.
