### ISSUE TITLE
Elytra plus

### ISSUE THREAD

**Issue by Andre-L8Bolt** [IUDevman/gamesense-client#34]
Yesterday I found out about this client — I love its customization options and *really* want to use it was my main client. Long story short, there are two features that I would deem as *essential* on minecraft anarchy servers like 9b9t or 2b2t. 
The most important one to me would be Elytra plus or Elytra flight. 

#### Kami blue's elytra fight module
Elytra flight is pretty self-explanatory and as of now [kami-blue](https://github.com/kami-blue/client) has my favorite elytra flight [module](https://github.com/kami-blue/client/blob/master/src/main/java/me/zeroeightsix/kami/module/modules/movement/ElytraFlight.kt) and is licensed under the LGPLv3 (which I think should be compatible).

#### some points for the elytra flight module:
- [ ] should have control Mode
- [ ] boost mode would be nice
- [ ] hopefully has some sort of speed control
- [ ] is probably under movement category or similar
- [ ] acceleration settings
- [ ] ability to go up and down
- [ ] should work on servers like 9b9t (2b2t's elytra flight is glitched and all fly hacks are now useless there)

I personally do not have a lot of experience with java (I am learning it in school right now), but I would greatly appreciate the addition of a feature similar to it.
For now I will experiment trying to add the module on my own. I will probably provide updates on how (if at all) it goes.

**Comment by linustouchtips** [comment]
1 problem.

kami blue is written in kotlin.

Also, forge exists so why don't you just use gamesense and kami blue together?

**Comment by natan515** [comment]
Kami blue is written in Koin and java

**Comment by PeppoNetwork** [comment]
> Kami blue is written in Kotlin and java

kotlin = java

**Comment by lukflug** [comment]
Kotlin isn't the same as Java. Kotlin can be used with Java, since it can be compiled for the JVM. The point is that we won't skid anything, if we can't make any improvements, and that this particular KAMI module is implemented in Kotlin, which would make it a lot harder to port, since GameSense is supposed to be a Java-only project.

**Comment by linustouchtips** [comment]
kami blue modules are written in kotlin, it's mixins are written in java. and the only people that say kotlin and java are the same  are people who don't know how code in either.
