### ISSUE TITLE
AutoCrystal Suggestions

### ISSUE THREAD

**Issue by notperry1234567890** [IUDevman/gamesense-client#44]
1.  Pause While Mining Option.
2.  Split Walls Range Into Break Walls Range And Place Walls Range As Walls Range Changes Both But Would Be Better To Have Two  Options For It In Certain PvP Cases.
3. Make MaxSelfDmg Not Only Check For Placing Crystals Dmg But Breaking Cause I've Kmsed Alot From It Not Checking If Crystals Do Tons Of Dmg When Breaking Instead Of Only Checking Placing.

That's It.

**Comment by Gopro336** [comment]
sequential timing like future 2.10 would be nice too

**Comment by Doogie13** [comment]
Maybe add base place (places a block of obby if there isn't any valid spots for crystals to make one)?

**Comment by yagel15637** [comment]
@Doogie13 base place will make the CA slower, so I don't think it's a good idea.

**Comment by Doogie13** [comment]
> @Doogie13 base place will make the CA slower, so I don't think it's a good idea.

Make it optional tho. So if pvping not at bedrock or whatever you can toggle it on. Maybe a separate module that places crystal bases?
