### ISSUE TITLE
Playertweaks 

### ISSUE THREAD

**Issue by Phantom568** [IUDevman/gamesense-client#45]
Please rewrite playertweaks specifically no slow as it currently conficts with clients and it causes a bug when eating and moving(most noticeable when using strafe and eating) which causes the player to long jump forwards then get rubber banded back. Also with some clients gui move doesn’t work(I’m using Rhack and gamesense)

**Comment by notperry1** [comment]
> Please rewrite playertweaks specifically no slow as it currently conficts with clients and it causes a bug when eating and moving(most noticeable when using strafe and eating) which causes the player to long jump forwards then get rubber banded back. Also with some clients gui move doesn’t work(I’m using Rhack and gamesense)

tbh they should also make it into there own modules instead of just in one module playertweaks
