### ISSUE TITLE
A smarter ca

### ISSUE THREAD

**Issue by natan515** [IUDevman/gamesense-client#48]
Hello, ur ca is already great (; but I thought about some stuff that can make it better.
Track player movement, if the client sees the player start to increase speed(He Enable speed) so the crystals would go forward to where he should go(looking at) And not crystals that are close to him.
Ping ca, have ur ca to know whats player ping, only if like beyond 100 so he can know which crystals he ruther use in places that the player moves or if he thinks he will be fast enough to place them all and break and then he place some and break non and with ping mode, he will know how much he can really place and destroy by the player ping. Ik it sounds weird so if u want me to explain it more let me know and I think it can be possible to code and be pretty helpful for players like me with 100~200 ping.
There are settings that tell the client when to put crystal, but what if ur at 1v1 and u can crystal him for 25 damage but it will do u 5? and u set min damage to 4? so the client gets to make a coalition like if the damage u do to another player is more than 4 times than how u get(min 10 damage he gets or something) and than u would take some more damage but u will make him shit tons more damage. Ik it all sounds long and weird so if u got questions let me know and if u don't want to add it all good! (; have a good day and great client!

**Comment by linustouchtips** [comment]
how dare you call the auto crystal a he!?!?! it's a she for your information.

**Comment by natan515** [comment]
I AM SO SORRY, tell her Natan515 is sending his sorry, and some money. ILY (; CRYSTAL AURA
