### ISSUE TITLE
reach

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#50]
**Is your feature request related to a problem? Please describe.**
Reach

**Describe the solution you'd like**
Reach (KA can do reach but a reach module to be able to reach manually would be poggers

**Describe alternatives you've considered**
Not asking for almost useless features for a client that nobody will use considering freecam is a thing

**Additional context**
Demoman?

**Comment by natan515** [comment]
Its built in into kill aura

**Comment by Doogie13** [comment]
I know. A separate module to help mine out people's homes would be good though (rather than using freecam)
