### ISSUE TITLE
Add packet fly[FEATURE]

### ISSUE THREAD

**Issue by natan515** [IUDevman/gamesense-client#52]
A packet fly that works on 2b2t, or just the pvp servers, rn no free client got a working packet fly not even pyro 1.4.1 crack. So if you would be able to add it, it would make this client a rly good client for pvp

**Comment by linustouchtips** [comment]
unfortunately, this feature probably not coming to gamesense anytime soon. I can't speak for Hoosiers but a good packetfly is a pain to make and I doubt Hoosiers would do it :P. If you're looking for a good packetfly, consider using future's or konas's.

**Comment by natan515** [comment]
I don't want to pay...

**Comment by Doogie13** [comment]
I don't think there is a free good packetfly rn. Future packetfly works on pvp servers with good settings

**Comment by linustouchtips** [comment]
phobos 1.5.4 has a usable one, wouldn't say it's good but it's usable

**Comment by natan515** [comment]
I mean I don't gave phobos files, cus if i would have i will be able to remove the rat and use it, let me know of u got it pls.

**Comment by Doogie13** [comment]
Dont quote me on this but gopro is trustes and he removed the rat

**Comment by natan515** [comment]
> 
> 
> Dont quote me on this but gopro is trusted and he removed the rat

ok

**Comment by natan515** [comment]
Can u explain why did u close it?

**Comment by frosthead69** [comment]
I have pyro pfly configs that work :p
