### ISSUE TITLE
Hole ESP changes [FEATURE]

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#57]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Hole ESP recognises holes 2 wide and highlights them in a different colour

**Describe alternatives you've considered**
Pyro ig

**Additional context**
![2020-12-17_17 40 35](https://user-images.githubusercontent.com/62295632/102524467-f718d480-4090-11eb-8c68-b4ff841bb092.png)
If you stand in the middle you are immune to crystals at your feet
![2020-12-17_17 41 34](https://user-images.githubusercontent.com/62295632/102524473-f97b2e80-4090-11eb-824a-a823c4a06356.png)
Both make you immune to crystals at your feet

**Comment by IUDevman** [comment]
Thanks for the images, I'll probably add this

**Comment by TechAle** [comment]
i'll add this on the next update

**Comment by IUDevman** [comment]
Added by 0b00101010
