### ISSUE TITLE
NoRender armour [FEATURE]

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#59]
**Is your feature request related to a problem? Please describe.**
armour go brr

**Describe the solution you'd like**
NoRender should include armour (as nametags can show that). Allows to see clearer who is who.
Should be able to turn off seperate armour pieces 

**Describe alternatives you've considered**
Kami blue (but seems to not work with something idk)

**Additional context**
no

**Comment by linustouchtips** [comment]
90% sure that this is already a feature

**Comment by Doogie13** [comment]
> 90% sure that this is already a feature

I'm dumb
