### ISSUE TITLE
Smart offhand [FEATURE]

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#62]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Offhand crystal should hold a totem when CA isn't on and optionally a gapple while in a hole (and CA isn't on)

**Describe alternatives you've considered**
Using wurst+2 offhand with its CA with place and destroy off bound to the same bind as gamesense CA.

**Additional context**
Wurst+2 offhand is identical to what I'm asking for.

**Comment by yagel15637** [comment]
I could write that, sure!

**Comment by Doogie13** [comment]
> I could write that, sure!

Thanks

**Comment by yagel15637** [comment]
oof i never wrote that
i should really think more before i commit to a project :(

**Comment by Doogie13** [comment]
kek
