### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Eskerepvp** [IUDevman/gamesense-client#65]
Make this utility mod "gamesense" compatible with the newest leaked utility mod named "phobos". The strong features such as, piston crystal, View Model, Go Hooisers dupe, and other quality of life features would go perfectly with phobos. With phobos's strong crystal aura and combat module they would be the perfect fit for the anarchy experience. The movement, modules render modules , misc modules ,etc would go perfect for the average anarchy player. Mixed in with phobos's very unique combat modules and advance crystal aura it would give a anarchy player the competitive edge in crystal combat.

**Comment by Doogie13** [comment]
1.7 Phobos is a rat I think
