### ISSUE TITLE
Use a separate hud editor [FEATURE]

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#66]
**Is your feature request related to a problem? Please describe.**
Clickgui is cluttered by default and a HUD editor is sipler than having both in the same place

**Describe the solution you'd like**
Hud editor with extras like totem count, time etc like salhack has.
I know there's an option to turn off those panels under clickgui but a separate hud editor would allow for smaller things that don't need their own modules (like totem count, crystal count, etc.). 

**Describe alternatives you've considered**
Salhack, w+2, xulu

**Additional context**
Idk if this should be posted in pannelstudio repo.

**Comment by IUDevman** [comment]
When you're done with placing your HUD components, you can toggle the "Show HUD Panels" option under the clickgui module to hide the boxes.

**Comment by Doogie13** [comment]
> When you're done with placing your HUD components, you can toggle the "Show HUD Panels" option under the clickgui module to hide the boxes.

Yes, but things like a totem counter etc don't need their own modules if they were implemented. Maybe add a HUD elements module that contains inv viewer, totem counter etc?
