### ISSUE TITLE
Phobos Compatibility [BUG]

### ISSUE THREAD

**Issue by Vhops** [IUDevman/gamesense-client#70]
Gamesense isn't compatible with phobos.

Here is the MultiMC logs for Gamesense 2.2.4 and Phobos 1.7.2 if it helps at all.

[log.txt](https://github.com/IUDevman/gamesense-client/files/5761241/log.txt)

**Comment by lukflug** [comment]
It is a known issue. You need to change a mixin on the Phobos side. There is not much we can do on the GameSense side to fix it.

**Comment by aesthetic0001** [comment]
@lukflug can you tell me which to change for 1.5.4?

**Comment by lukflug** [comment]
The newest GameSense version should have improved Phobos compatibility. Some users posted instructions and jars for patched Phobos on the GameSense discord and other forums. This is however not Phobos technical support.

**Comment by aesthetic0001** [comment]
Thanks!
