### ISSUE TITLE
[BUG] totem counter broken pow pow

### ISSUE THREAD

**Issue by moomooooo** [IUDevman/gamesense-client#79]
**Describe the bug**
ur totem counter doesent account for the offhand in cyber's combat info

**To Reproduce**
put a totem in ur offhand and look at how the number doesent increase 0_0

**Expected behavior**
the number doesn't increase.

**Screenshots**
no lol

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser opera gx on top
 - Version gamesense version? if so whatever the latest one is, 2.2.5 i think

**Additional context**
its in combat info u can fix by adding...
if (mc.player.getHeldItemOffhand().getItem() == Items.TOTEM_OF_UNDYING)
	    		list.totems++;
 thanks

**Comment by IUDevman** [comment]
I'll look into this, thanks 👍
