### ISSUE TITLE
Packet Eat [FEATURE]

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#81]
**Is your feature request related to a problem? Please describe.**
nom

**Describe the solution you'd like**
a module where you instantly eat food like in momentum client

**Describe alternatives you've considered**
momentum client 

**Additional context**
https://cdn.discordapp.com/attachments/755169316659265547/774385396586905631/Screen_Recording_2020-11-06_at_1.27.41_PM.mov

**Comment by IUDevman** [comment]
added

**Comment by linustouchtips** [comment]
based
