### ISSUE TITLE
NoRender Enemy Hurtcam [FEATURE]

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#82]
**Is your feature request related to a problem? Please describe.**
Basically, nocluster is functionally limited because of the hurtcam.

**Describe the solution you'd like**
Alongside making the player translucent, make the hurtcam translucent/invisible so when you do damage to the enemy you are inside, hitting them doesn't obscure your view

**Describe alternatives you've considered**
fortnite

**Additional context**

**Comment by IUDevman** [comment]
Can you post a picture/video of what you see when this happens?

**Comment by IUDevman** [comment]
added
