### ISSUE TITLE
Gradient/UFO hole esp

### ISSUE THREAD

**Issue by TerikKek** [IUDevman/gamesense-client#84]
**Describe the solution you'd like**
ik phobos has the UFO hole esp and pyro has a bad version of the gradient
[phobos UFO](https://gofuckyourselfyouarearetard.com/embed/iXZW7f17gm.png?key=isSOiPMQJQWuss&color=009eff&title=Terik) pyro has the same thing but reversed 
**Describe alternatives you've considered**
keep current hole esp

**Additional context**
would look cool and i would start using gamesense again if it were added

**Comment by TerikKek** [comment]
[another example](https://cocaine.supply/embed/5Lt1TnetVV.png?key=U5aC0PDZQpj15w&color=009eff&title=Terik)

**Comment by IUDevman** [comment]
@lukflug Wanna look into making this?

**Comment by lukflug** [comment]
Done with PR #102
