### ISSUE TITLE
[FEATURE] Auto Kit

### ISSUE THREAD

**Issue by wat111** [IUDevman/gamesense-client#85]
**Is your feature request related to a problem? Please describe.**
Not a problem but I think it would be helpful

**Describe the solution you'd like**
Auto Kit: basically in the module settings on some it lets u choose what kit and server it should /kit on

**Describe alternatives you've considered**
Uh idk I just thought it could be cool

**Additional context**

**Comment by IUDevman** [comment]
Not really planning on adding an AutoKit module for now, I will reopen this issue in the future if I/someone decide to work on it.
