### ISSUE TITLE
[FEATURE] Add all branches to actions tab 

### ISSUE THREAD

**Issue by Doogie13** [IUDevman/gamesense-client#94]
**Is your feature request related to a problem? Please describe.**
I can't build gamesense for some reason and have no idea why

**Describe the solution you'd like**
Enable v2.2.6 and any other new branches to the actions tab

**Describe alternatives you've considered**
Having a breakdown on the discord until someone dms me a built jar

**Additional context**
Only the main branch has actions enabled

**Comment by TechAle** [comment]
i'll send to you 2.2.6

**Comment by lukflug** [comment]
I removed the branch condition on the workflow. It now compiles for every branch.

**Comment by Doogie13** [comment]
Ty
